### ISSUE TITLE
code smell on if-else lookup

### ISSUE THREAD

**Issue by pearsonca** [tjhladish/ebola_ring#1]
https://github.com/tjhladish/ebola_ring/blob/29ef059da853a47b7b1a62660933354165250d79/Event_Driven_Polio_Sim.h#L88

Code smell: I prefer this sort of thing to be defined as a const map<enum, int> lookup, rather than if else.

Though: could also be done as list / array look up, given how enum works?

**Comment by tjhladish** [comment]
If the sampling were going to stay this simple, I would use a vector<double>; however, we need to be able to support distributions/more complex sampling logic.  Don't mind the code smell, it is but a passing stench.

As an aside, a switch-case isn't exactly the same as an if-else.  Switch-cases are preferred for this sort of thing over if-elses because the compiler can potentially optimize them better.
